[feat/#1] 1주차 과제 구현
AND-SOPT-ANDROID/jihyeon-jin pull request #2
Opened 2024-10-11 05:58 UTC by serioushyeon

## Related issue 🛠
- closed #1 

## Work Description ✏️
- 회원가입
- 로그인
- 마이페이지 
- 자동 로그인
-  로그아웃
- SingleLine
- imeAction
- Ripple 제거

## Screenshot 📸

https://github.com/user-attachments/assets/d4b540cb-409f-443b-848e-b1fb62facdac

https://github.com/user-attachments/assets/fbbf7ef4-9d63-4c22-a677-3bfdf0eb93ac

https://github.com/user-attachments/assets/c34cf888-3769-4c53-97a1-4814010ae3c0

https://github.com/user-attachments/assets/b55e883b-677b-4676-8c13-d1c51ce67bd3

## Uncompleted Tasks 😅
- [ ] 뷰모델 활용
- [ ] 키보드가 버튼 가리지 않게 설계

## To Reviewers 📢
Compose 첫 도전이라 많이 난잡한 코드가 되었네요...🥲
뷰모델까지 적용하고 싶었는데 시간이 모자랄 것 같아서 추후에 할 예정입니다!ㅜㅜ
remember, launcheffect 등 처음 접해보는 것들이 나와서 많이 헤맸지만 많이 배웠습니다
더 배우고 싶어요! 피드백 너무너무 환영합니다 많이 남겨주세요!🤗

2024-10-11 08:42 UTC, kangyein9892 approved these changes
컴포넌트 디렉토리 구조 하나하나씩 나눠서 한거 깔끔하고 좋은 것 같아요 ! 많은 걸 배워갑니다 짱짱 수고하셧어요 🥰

2024-10-11 08:42 UTC, kangyein9892 commented on app/src/main/java/org/sopt/and/extension/ModifierExtension.kt
> +}
다른 분들 거에서는 onClick만 본 것 같은데 onLongClick도 있네요,,,! 둘의 차이점이 있을까요?

2024-10-11 08:42 UTC, kangyein9892 commented on app/src/main/java/org/sopt/and/ui/mypage/MyActivity.kt
> +                        })
```suggestion
       MyScreen(
        modifier = Modifier.padding(innerPadding), 
        email = id, 
        onLogoutButtonPress = {
            PreferenceUtils.clearAll(context = context)
            Toast.makeText(context,
            getString(R.string.my_page_toast_success_logout), Toast.LENGTH_SHORT).show()
            val intent = Intent(context, SignInActivity::class.java)
            startActivity(intent)
            finish()
    })                 
```

한꺼번에 인자를 작성하니까 뭔가 가독성이 떨어지는 것 같아서 이런식으로 하나씩 작성해주면 좋을 것 같다는 생각이 들어요!

2024-10-11 08:42 UTC, kangyein9892 commented on app/src/main/java/org/sopt/and/ui/sign/SignInActivity.kt
> +        }
이렇게 컴포저블 함수에서 activityResult를 사용해볼 수 있다니... 생각하지도 못했는데 우와 방법 알아갑니다 😊

2024-10-11 08:42 UTC, kangyein9892 commented on app/src/main/java/org/sopt/and/ui/sign/SignInScreen.kt
> +                 onSignInButtonClick: () -> Unit) {
```suggestion
  fun SignInScreen(
        modifier: Modifier = Modifier,
        email: String,
        password: String,
        onEmailChange: (String) -> Unit,
        onPasswordChange: (String) -> Unit,
        onSignUpButtonClick: () -> Unit,
        onSignInButtonClick: () -> Unit) {
```
코드 개행 요런식으로 바꿔주면 더 좋을 것 같다는 생각이 들어요 ! 가독성 측면에서 뭔가 더 좋아보이네요!

2024-10-11 08:42 UTC, kangyein9892 commented on app/src/main/java/org/sopt/and/ui/sign/SignUpScreen.kt
> +{
요기도 신경써주면 좋을것 같아요 !!

2024-10-11 08:42 UTC, kangyein9892 commented on app/src/main/java/org/sopt/and/ui/sign/SignUpScreen.kt
> +                            .show()
사소한 거 지만... 위와 밑에 show() 위치가 다르네요 !! 아니면 다른 분들 처럼 확장함수 사용해도 좋을 것 가탕요 ~~

2024-10-11 08:42 UTC, kangyein9892 commented on app/src/main/java/org/sopt/and/ui/sign/component/SignUpPasswordField.kt
> +) {
위에 waveCommonPasswordField랑 다른 점이 있을까요? isValid 때문에 두가지를 분리해서 사용한건지 궁금해요!

2024-10-11 08:54 UTC, jm991014 approved these changes
전반적으로 함수 네이밍이 명확해서 보기 편했습니다~ 
전혀 컴포즈가 처음같지 않아요.. 잘하십니다!! 멋져요 ㅋ

2024-10-11 08:54 UTC, jm991014 commented on app/src/main/java/org/sopt/and/MainActivity.kt
> +        val intent = if (id.isNotBlank() && pw.isNotBlank()) {
단순 궁금증입니다! 혹시 isNotEmpty() 대신 isNotBlank()를 사용하신 이유가 따로 있나요?

2024-10-11 08:54 UTC, jm991014 commented on app/src/main/java/org/sopt/and/ui/component/textField/WavveCommonPasswordField.kt
> +
TextField 커스텀이 야무지네요.. BasicTextField를 사용하면 제가 겪은 trailIcon 공간 문제가 안 생기는거 같네요, 배워갑니다! 그리고 WavveCommonTextField랑 코드가 거의 동일해보이는데 인자로 isPassword: Boolean 값만 넘겨서 아래 hide, show를 보이도록 설정하는건 어떤가요?

2024-10-11 08:54 UTC, jm991014 commented on app/src/main/java/org/sopt/and/ui/sign/SignUpScreen.kt
> +}
이거!!! 제가 구현하려다 포기하고 스낵바로 넘어갔는데 참고해갑니다~

2024-10-11 08:56 UTC, jm991014 commented on app/src/main/java/org/sopt/and/ui/sign/SignInScreen.kt
> +                 onSignInButtonClick: () -> Unit) {
제 리뷰에 있는 내용이긴 한데, 조장님께서 남겨주신 컴포즈 인자 컨벤션 한 번 참고하시면 좋을 것 같아요!

2024-10-11 08:58 UTC, boiledEgg-s requested changes
와,, 진짜 너무 잘하십니다,, 흠 잡을데가 없네요,,
우리 조 뭐임? 왜 다 잘함?

2024-10-11 08:58 UTC, boiledEgg-s commented on app/src/main/java/org/sopt/and/extension/ModifierExtension.kt
> +        onLongClick = { onLongClick() },
여기엔 중괄호를 안써도 될 것 같아요!
인자가 없거나, 람다와 함수의 인자 순서가 같다면 중괄호를 사용하지 않아도 된답니다!
```suggestion
        onClick = onClick,
        onLongClick = onLongClick,
```

2024-10-11 08:58 UTC, boiledEgg-s commented on app/src/main/java/org/sopt/and/ui/component/textField/WavveCommonTextField.kt
> +                keyboardController?.hide()
저는 이런 부분까진 신경을 못 썼는데 꼼꼼하시네요😮

2024-10-11 08:58 UTC, boiledEgg-s commented on app/src/main/java/org/sopt/and/ui/component/topBar/CloseTopBar.kt
> +            titleContentColor = Color.White
색상들 테마에 변수화해서 사용하는거 너무 좋네요! 저도 담 과제엔 적용해야겠어요ㅎㅎ
 
기왕이면 안드로이드에서 기본으로 제공해주는 White, Black 등의 색상들도 테마에 따로 저장해서 사용하는게 더 좋을 것 같아요!!

2024-10-11 08:58 UTC, boiledEgg-s commented on app/src/main/java/org/sopt/and/ui/mypage/MyActivity.kt
> +                }) { innerPadding ->
줄바꿈은 함수 가독성을 높여줍니다! 
컴포저블 함수를 호출할 땐 왠만하면 한 줄에 인자 하나를 적어주도록 합시다~

2024-10-11 08:58 UTC, boiledEgg-s commented on app/src/main/java/org/sopt/and/ui/mypage/MyScreen.kt
> +    onLogoutButtonPress: () -> Unit
컴포저블의 인자 순서는 다음과 같아요:
1. 필수 인자
2. 수정자
3. 선택 인자

이 컨벤션을 지킵시다~

2024-10-11 08:58 UTC, boiledEgg-s commented on app/src/main/java/org/sopt/and/ui/mypage/MyScreen.kt
> +                }
이건 Modifier 확장함수로 빼두신거 아닌가요?

2024-10-11 08:58 UTC, boiledEgg-s commented on app/src/main/java/org/sopt/and/ui/mypage/component/MyPageContents.kt
> +                contentDescription = "No Content",
-하드코딩 감지-

2024-10-11 08:58 UTC, boiledEgg-s commented on app/src/main/java/org/sopt/and/ui/sign/SignInScreen.kt
> +                 onSignInButtonClick: () -> Unit) {
줄바꿈 + 인자 순서 예시입니다!
```suggestion
fun SignInScreen(
     email: String,
     password: String,
     onEmailChange: (String) -> Unit,
     onPasswordChange: (String) -> Unit,
     onSignUpButtonClick: () -> Unit,
     onSignInButtonClick: () -> Unit,
     modifier: Modifier = Modifier,
) {
```

2024-10-11 08:58 UTC, boiledEgg-s commented on app/src/main/java/org/sopt/and/ui/sign/SignInScreen.kt
> +                .noRippleClickable()
Button에도 기본적으로 리플효과가 있나요?
만들어두신 noRippleClickable은 버튼 클릭 시 실행할 함수를 같이 받아서 사용하도록 구현된 것 같은데,
noRippleClickable과 버튼의 onClick을 동시에 사용하신 이유가 있나요?

2024-10-11 08:58 UTC, boiledEgg-s commented on app/src/main/java/org/sopt/and/ui/sign/SignUpActivity.kt
> +                            intent.putExtra("PASSWORD", password)
이런 문자열들도 상수화를 하여 사용하면 혼란을 줄일 수 있습니다!!
분명 로그인 화면에서 이 값들을 참조할텐데 하드코딩해두면 키값을 다르게 설정해서 오류가 발생할 수 있겠죠?
이런 오류들이 은근 찾기 어려워요ㅎㅎ

2024-10-11 10:42 UTC, unam98 reviewed
안녕하세요 명예 ob 리뷰어로 참여하게된 김우남이라고 합니다~! 👍🏻

2024-10-11 10:42 UTC, unam98 commented on app/src/main/java/org/sopt/and/utils/PreferenceUtils.kt
> +        prefs.edit().putString(KEY_USER_ID, userId).apply()
SharedPreference에서 commit() 또는 apply()를 사용할 수 있는데 apply를 사용하신 이유가 있으실까요?

이 두개에 대한 차이점 공식문서 한 번 읽어보시는 것을 추천드립니다!

2024-10-11 10:42 UTC, unam98 commented on app/src/main/java/org/sopt/and/utils/PreferenceUtils.kt
> +        prefs.edit().putString(KEY_USER_ID, userId).apply()
추가로 아래 케이스들에 대해서도 참고를 해보시면 좋을 것 같습니다 :)

- SharedPreference와 같은 로컬 db는 앱을 삭제해도 data가 남아있기 때문에 이 점을 고려하여 더 이상 필요하지 않게 되었을 땐 저장된 값을 비워주는 것이 좋습니다.

- 공식문서에서 DataStore 사용을 권장하고 있는데 SharedPreference와 비교해서 어떤 차이점이 있는지 코드랩 찾아보시면 도움이 될 것 같습니다.

- EncryptedSharedPreference라는 것에 대해서도 서칭을 해보시면 좋을 것 같아요!

2024-10-11 10:42 UTC, unam98 commented on app/src/main/java/org/sopt/and/utils/PreferenceUtils.kt
> +object PreferenceUtils {
코틀린에선 싱글톤을 구현할 때 object 말고도 companion object를 쓸 수 있는데 이 두개는 어떤 차이점이 있을까요?

2024-10-11 10:42 UTC, unam98 commented on app/src/main/java/org/sopt/and/utils/PreferenceUtils.kt
> +    private const val PREFS_NAME = "wavve_prefs"
const val과 val의 차이는 무엇일까요?

2024-10-11 10:42 UTC, unam98 commented on app/src/main/java/org/sopt/and/ui/sign/component/SignUpPasswordField.kt
> +    var isFocused by remember { mutableStateOf(false) }
by 키워드를 사용하면 어떤 효용이 있나요?

2024-10-11 10:42 UTC, unam98 commented on app/src/main/java/org/sopt/and/MainActivity.kt
>      override fun onCreate(savedInstanceState: Bundle?) {
savedInstanceState는 무엇인가요?

2024-10-11 10:42 UTC, unam98 commented on app/src/main/java/org/sopt/and/MainActivity.kt
>      override fun onCreate(savedInstanceState: Bundle?) {
Bundle을 활용하여 data를 저장하는 것과 뷰모델 내에 data를 저장하는 것 간에는 어떤 차이와 장단점이 있을까요?

2024-10-11 10:42 UTC, unam98 commented on app/build.gradle.kts
> +        sourceCompatibility = JavaVersion.VERSION_11
자바 11로 설정하신 의도가 있나요?

2024-10-11 10:42 UTC, unam98 commented on app/src/main/java/org/sopt/and/extension/ModifierExtension.kt
> +inline fun Modifier.noRippleClickable(
inline 함수는 어떤 목적으로 사용하셨나요?

2024-10-13 10:47 UTC, serioushyeon commented on app/src/main/java/org/sopt/and/extension/ModifierExtension.kt
> +}
그냥 클릭과 길게 클릭했을때인 롱클릭 두개를 모두 처리하는 함수와, onClick만 처리하는 함수입니다!

2024-10-13 10:48 UTC, serioushyeon commented on app/src/main/java/org/sopt/and/ui/mypage/MyActivity.kt
> +                        })
좋네요!! 참고하겠습니다😇😇

2024-10-13 10:49 UTC, serioushyeon commented on app/src/main/java/org/sopt/and/ui/sign/SignInScreen.kt
> +                 onSignInButtonClick: () -> Unit) {
감사합니다!! 컨벤션이 있었군요!

2024-10-13 10:50 UTC, serioushyeon commented on app/src/main/java/org/sopt/and/ui/sign/SignUpScreen.kt
> +                            .show()
디테일한 부분을 놓쳤네요 감사합니다!!

2024-10-13 10:51 UTC, serioushyeon commented on app/src/main/java/org/sopt/and/ui/sign/component/SignUpPasswordField.kt
> +) {
코드를 볼 때 조금 더 직관적으로 보이기 위해 분리를 해두었는데요 재사용 측면에서 합치는 것도 좋을 것 같네요!

2024-10-13 10:53 UTC, serioushyeon commented on app/src/main/java/org/sopt/and/MainActivity.kt
> +        val intent = if (id.isNotBlank() && pw.isNotBlank()) {
단순히 공백하나만 입력한 것도 빈값으로 구분하기 위해 사용하였습니다!

2024-10-13 10:53 UTC, serioushyeon commented on app/src/main/java/org/sopt/and/ui/component/textField/WavveCommonPasswordField.kt
> +
코드를 볼 때 조금 더 직관적으로 보이기 위해 분리를 해두었는데요 재사용 측면에서 합치는 것도 좋을 것 같네요!

2024-10-13 10:54 UTC, serioushyeon commented on app/src/main/java/org/sopt/and/extension/ModifierExtension.kt
> +        onLongClick = { onLongClick() },
가독성을 위해 좋을 것 같네요 감사합니다!

2024-10-13 10:56 UTC, serioushyeon commented on app/src/main/java/org/sopt/and/ui/mypage/MyScreen.kt
> +                }
앗 빼두었는데 디테일한 부분을 놓쳤네요..!

2024-10-13 10:56 UTC, serioushyeon commented on app/src/main/java/org/sopt/and/ui/mypage/MyScreen.kt
> +    onLogoutButtonPress: () -> Unit
컨벤션 새로 알아갑니다!

2024-10-13 10:56 UTC, serioushyeon commented on app/src/main/java/org/sopt/and/ui/mypage/component/MyPageContents.kt
> +                contentDescription = "No Content",
헉...

2024-10-13 10:56 UTC, serioushyeon commented on app/src/main/java/org/sopt/and/ui/sign/SignInScreen.kt
> +                 onSignInButtonClick: () -> Unit) {
감사합니다!

2024-10-13 10:57 UTC, serioushyeon commented on app/src/main/java/org/sopt/and/ui/sign/SignInScreen.kt
> +                .noRippleClickable()
구현을 마치고 추가하다보니 리플 제거 쪽 디테일을 많이 놓쳤네요 ㅜㅜ 참고하겠습니다!

2024-10-13 10:57 UTC, serioushyeon commented on app/src/main/java/org/sopt/and/ui/sign/SignUpActivity.kt
> +                            intent.putExtra("PASSWORD", password)
와! 확실히 좋네요 감사합니다!

2024-10-13 11:05 UTC, serioushyeon commented on app/src/main/java/org/sopt/and/utils/PreferenceUtils.kt
> +        prefs.edit().putString(KEY_USER_ID, userId).apply()
상세한 코멘트 감사합니다!👍 apply를 사용한건 흔히 쓰는 방식이라 별생각 없이 사용했는데 찾아보니 동기적, 비동기적이라는 차이가 있었네요! data store, encrytedshaerdpreference에 대해서도 공부해보도록 하겠습니다!

2024-10-13 11:09 UTC, serioushyeon commented on app/src/main/java/org/sopt/and/utils/PreferenceUtils.kt
> +object PreferenceUtils {
companion object는 클래스의 일부로 동작하기에 특정 클래스와 연관이 있는 싱글톤이며 반연에 object는 특정 클래스와 연관이 있지 않은 전역 싱글톤입니다 sharedprefernce는 전역에서 특정클래스와 관계없이 사용할것이기 때문에 object가 적합하다고 생각이 들어 사용하였습니다!

2024-10-13 11:11 UTC, serioushyeon commented on app/src/main/java/org/sopt/and/utils/PreferenceUtils.kt
> +    private const val PREFS_NAME = "wavve_prefs"
const val은 컴파일 시점 값이 결정되기에 인스턴스 없이 접근가능하며 전역상수로 주로 쓰이며, val은 런타임 시점에 값이 결정되어 인스턴스가 필요할 수 있습니다 객체나 컬렉션 등 복잡한 타입을 다룰 때 사용합니다!

2024-10-13 11:14 UTC, serioushyeon commented on app/src/main/java/org/sopt/and/ui/sign/component/SignUpPasswordField.kt
> +    var isFocused by remember { mutableStateOf(false) }
프로퍼티 위임으로 코드를 더욱 간결하게 사용할 수 있으며 일반 변수처럼 사용할 수 있게합니다!

2024-10-13 11:15 UTC, serioushyeon commented on app/src/main/java/org/sopt/and/MainActivity.kt
>      override fun onCreate(savedInstanceState: Bundle?) {
액티비티나 프래그먼트가 소멸되었다가 다시 생성될때, 원래 상태를 복원하기 위해 사용되는 번들입니다. 이를 통해 예기치 못하게 액티비티나 프래그먼트가 소멸될 시 사용자가 입력한 데이터나 ui를 저장하고 복원할 수 있습니다

2024-10-13 11:16 UTC, serioushyeon commented on app/build.gradle.kts
> +        sourceCompatibility = JavaVersion.VERSION_11
안드로이드 스튜디오에서 제 컴퓨터 설정에 맞게 자동으로 바꾼 것 같습니다...!

2024-10-13 11:19 UTC, serioushyeon commented on app/src/main/java/org/sopt/and/MainActivity.kt
>      override fun onCreate(savedInstanceState: Bundle?) {
UI 상태와 같은 일시적인 데이터를 저장하는 데 적합하고, 프로세스 종료 후에도 데이터 복원이 가능하지만 저장할 수 있는 데이터 크기와 타입이 제한적입니다! ViewModel은 비즈니스 로직이나 복잡한 상태 관리에 적합합니다. 하지만 프로세스가 종료되면 데이터가 소멸할 수 있어 장기적인 상태 보존이 필요할 경우 추가적인  방법이 필요합니다!

2024-10-13 11:24 UTC, serioushyeon commented on app/src/main/java/org/sopt/and/extension/ModifierExtension.kt
> +inline fun Modifier.noRippleClickable(
inline 함수는 호출 오버헤드를 줄여주기 때문입니다. 일반적인 함수 호출은 스택에 함수 호출 정보를 저장하고 점프하는 작업이 필요하지만 inline 함수는 함수 호출을 하지 않고 해당 위치에 함수 본문이 직접 삽입됩니다. 따라서 noRippleClickable처럼 짧은 함수일 경우 성능 최적화에 유리합니다 또한 UI 구성 요소에 자주 사용되기 때문에, 반복적으로 호출됩니다.특히 Modifier는 짧고 자주 호출되는 함수가 많아서 inline을 통해 불필요한 함수 호출과 오버헤드를 줄이기 위해 사용되었습니다!

2024-10-13 12:22 UTC, unam98 commented on app/src/main/java/org/sopt/and/MainActivity.kt
>      override fun onCreate(savedInstanceState: Bundle?) {
> 예기치 못하게

이 부분 관련하여 알아두시면 좋은 점이 있어 추가 질문 드립니다!

- savedInstanceState에 data를 저장하는 함수가 호출되는 생명주기 시점은 언제일까요?
- 위 함수는 특정 생명주기에서 '항상' 호출이 될까요?

2024-10-13 12:26 UTC, unam98 commented on app/src/main/java/org/sopt/and/MainActivity.kt
>      override fun onCreate(savedInstanceState: Bundle?) {
> 프로세스가 종료되면

- 프로세스가 종료되는 기준이 있을까요?
- LMK, OOM에 대해서도 서칭을 한 번 해보시면 도움이 될 것 같습니다 :)

> ViewModel

- AAC ViewModel과 MVVM에서 말하는 ViewModel은 같은 것일까요?
- configuration change가 일어났을 때와 finish()를 호출했을 때 모두 액티비티 인스턴스가 onDestroy() 콜백을 타서 파괴됩니다. 그런데 전자의 경우엔 AAC ViewModel 객체가 살아있고 후자의 경우엔 AAC ViewModel 객체가 파괴되는 이유는 무엇일까요?

2024-10-13 12:29 UTC, unam98 commented on app/src/main/java/org/sopt/and/utils/PreferenceUtils.kt
> +object PreferenceUtils {
companion object와 object의 초기화 시점은 모두 동일할까요?

2024-10-13 12:39 UTC, unam98 commented on app/src/main/java/org/sopt/and/MainActivity.kt
>      override fun onCreate(savedInstanceState: Bundle?) {
@jm991014 @boiledEgg-s @kangyein9892 
제가 지현님 pr에 댓글을 많이 달게 되었는데 참고해보시면 좋을 것 같습니다 :)

2024-10-13 12:55 UTC, serioushyeon commented on app/src/main/java/org/sopt/and/utils/PreferenceUtils.kt
> +object PreferenceUtils {
다릅니다! companion object는 클래스가 처음 로드될 때 초기화되고  object는 객체가 처음 사용될 때 초기화됩니다! (실제로 사용될 때 초기화, 또한 애플리케이션이 수명 주기 동안 메모리에 유지되며, 애플리케이션이 종료될 때 삭제, companion object는 일반적으로 클래스가 메모리가 제거되면 companion object도 함께 제거)
코멘트를 달면서 추가적으로 공부하게 되어 좋네요 감사합니다 ㅜㅜ

2024-10-13 13:19 UTC, serioushyeon commented on app/src/main/java/org/sopt/and/MainActivity.kt
>      override fun onCreate(savedInstanceState: Bundle?) {
onCreate(), onSaveInstanceState(), onRestoreInstanceState() 함수는 모두 Bundle 객체를 매개변수로 갖기때문에 이 객체를 이용해 데이터를 저장하고 복원할 수 있습니다! 데이터를 저장하고 복구하는 이유는 유저가 액티비티의 재생성을 인지하지 못하게 하기 위함입니다. 
또한 savedInstanceState에 데이터를 저장하는 함수는 onSaveInstanceState()입니다. (대게 onStop() 직후에 호출, 근데 알아보니 OS 버전에 따라 onStop()보다 먼저 호출되기도 한다고 하네요..!!) 저장하고 싶은 상태가 있다면 onSaveInstanceState()의 인자로 받는 Bundle outState에 담아두면 됩니다.
상태 복구는 onCreate()또는 onRestoreInstanceState() 에 이루어집니다.
하지만 onStop()이 불린다고 해서 onSaveInstanceState()가 항상 불리는 건 아닙니다!
onSaveInstanceState()는 시스템에 의해 액티비티가 예기치 않게 종료되는 경우에만 호출됩니다. 
(사용자가 명시적으로 앱을 종료하거나 finish()를 호출할 경우, 뒤로가기로 종료시 onSaveInstanceState()는 호출되지 않습니다.)
예기치 못한 상황이라는 것은 화면 회전, 메모리 부족 인해 종료될 때 등에 호출됩니다!

2024-10-13 13:59 UTC, unam98 commented on app/src/main/java/org/sopt/and/MainActivity.kt
>      override fun onCreate(savedInstanceState: Bundle?) {
> onSaveInstanceState()는 시스템에 의해 액티비티가 예기치 않게 종료되는 경우에만 호출됩니다.

이 부분 출처가 어디인가요?!

2024-10-13 14:07 UTC, unam98 commented on app/src/main/java/org/sopt/and/MainActivity.kt
>      override fun onCreate(savedInstanceState: Bundle?) {
> Bundle 객체를 매개변수로 갖기때문에 이 객체를 이용해 데이터를 저장하고 복원할 수 있습니다!

Bundle은 내부적으로 직렬화 과정을 거쳐서 data를 저장하는데

직렬화 관련하여 알아두시면 좋은 내용이 있어 추가 질문 드립니다.

- 안드로이드에서 직렬화에 쓰이는 기술들로 parcelize나 serialize가 있는데 이 두개는 어떤 차이점 및 장단점이 있을까요?

- 객체를 intent를 통해서 다른 activity로 넘길 때 필히 직렬화를 해주어야 하는데 이유가 무엇일까요?

제가 꼬리 질문을 많이 달고 있는데 여유 되실 때 보셔도 됩니다 😅 조금 어렵고 시간이 걸리시겠지만 분명 도움이 될 거예요!

2024-10-14 00:36 UTC, boiledEgg-s approved these changes
너무 고생하셨습니다! 제 수준에선 더 지적할게 없네요,,
2주차도 화이팅~

2024-10-14 00:36 UTC, boiledEgg-s commented on app/src/main/java/org/sopt/and/ui/mypage/MyActivity.kt
> +                    }
조건문으로 분리할 땐 최대한 작은 부분을 분리하는게 가독성 측면에서 좋을 것 같아요!
지금의 경우, `onLogoutButtonPress`만 달라지기 때문에 그 부분에 대한 조건문으로 바뀌면 좋겠네요!

2024-10-14 00:36 UTC, boiledEgg-s commented on app/src/main/java/org/sopt/and/ui/sign/SignUpActivity.kt
> +    }
companion object는 보통 클래스 하단에서 선언된다고 합니다!

2024-10-14 00:37 UTC, boiledEgg-s commented on app/src/main/java/org/sopt/and/MainActivity.kt
>      override fun onCreate(savedInstanceState: Bundle?) {
너무 유익하네요!! 저도 공부해보겠습니다~

2024-10-14 02:43 UTC, merged

2024-10-16 10:03 UTC, jihyunniiii reviewed
제가 너무 늦게 리뷰를 달았죠? ㅠㅠ 죄송합니다
고생하셨어요

2024-10-16 10:03 UTC, jihyunniiii commented on app/src/main/AndroidManifest.xml
> +            android:theme="@style/Theme.ANDANDROID" />
지금 application에서 theme를 설정해주고 있죠?
이렇게 설정하면 해당 theme이 기본 theme가 됩니다.
activity에서 기본 theme을 사용하고자한다면, activity에 theme를 중복으로 설정해주지 않아도 됩니다.

2024-10-16 10:03 UTC, jihyunniiii commented on app/src/main/java/org/sopt/and/ui/mypage/MyActivity.kt
> +            val message = intent.getStringExtra("SNACKBAR_MESSAGE") ?: ""
val message = intent.getStringExtra("SNACKBAR_MESSAGE").orEmpty()
이런 식으로 작성하실 수도 있습니다.

2024-10-16 10:03 UTC, jihyunniiii commented on app/src/main/java/org/sopt/and/ui/mypage/MyScreen.kt
> +                text = "${email}님",
이 부분도 %s님 이런 식으로 String 추출이 가능합니다.

2024-10-16 10:03 UTC, jihyunniiii commented on app/src/main/java/org/sopt/and/ui/sign/SignInActivity.kt
> +    private var password = ""
항상 묶음으로 관리되면 data class를 사용하시는 것도 좋겠네요!

2024-10-16 10:03 UTC, jihyunniiii commented on app/src/main/java/org/sopt/and/ui/sign/SignInActivity.kt
> +                    topBar = { BackButtonTopBar({ /*뒤로가기처리*/}) },
TODO 주석을 사용해보시는 것도 추천 드립니다.

2024-10-16 10:03 UTC, jihyunniiii commented on app/src/main/java/org/sopt/and/ui/sign/SignInActivity.kt
> +                email = data?.getStringExtra("EMAIL") ?: ""
만약 EMAIL을 email 등으로 잘못 입력하게 된다면 원하는 값을 불러올 수 없겠죠? (값을 불러올 때와 저장할 때 모두 같은 값을 사용해야 하니까요!)
이를 방지하기 위해 해당 값들은 상수화 시켜두는 것이 좋습니다.